FROM maven:3.8.4-openjdk-11-slim AS maven_build

WORKDIR /app

COPY pom.xml .
COPY src ./src

RUN mvn clean package -DskipTests

FROM openjdk:11-slim

WORKDIR /app

COPY --from=maven_build /app/target/*.jar app.jar

ENTRYPOINT ["java", "-Xmx2048M", "-jar", "app.jar"]