FROM maven:3.9.8-eclipse-temurin-21-alpine AS maven_build

WORKDIR /app

COPY pom.xml .
COPY src ./src

RUN mvn clean package -DskipTests

FROM openjdk:21-slim

COPY --from=maven_build /app/target/*.jar app.jar

ENTRYPOINT ["java", "-Xmx2048M", "-jar", "app.jar"]