spring:
  application:
    name: caixabank-test
  #datasource:
   # url: jdbc:postgresql://localhost:5432/my-database
   # username: user
   # password: password
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate.generate_statistics: true

logging:
  level:
    org:
      hibernate:
        stat: DEBUG
        SQL: DEBUG
